using System;
using System.Collections.Generic;
using System.Text;

namespace PLMSide.Data.Entites
{
    public class POS_MasterImport
    {
        public string Seg_Business_forbuy { get; set; }
        public string Seg_Business { get; set; }
        public string BRANCH_CN { get; set; }
        public string Seg_Marketplace_recommended { get; set; }
        public string BLRQ3 { get; set; }
        public string Division_Gender_Cluster_AppWomen { get; set; }
        public string Category_Cluster_Basketball { get; set; }
        public string OLD_POS_CODE { get; set; }
        public string AP_POS_BUY { get; set; }
        public string STA_BULK_KIDS { get; set; }
        public string PROVINCE_CN { get; set; }
        public string STC_OCS { get; set; }
        public string Category_Cluster_recommended_Running { get; set; }
        public string Division_Gender_Cluster_forbuy_AppWomen { get; set; }
        public string Comments { get; set; }
        public string Division_Gender_Cluster_recommended_FTWWomen { get; set; }
        public string Grading_OCS_forbuy { get; set; }
        public string POS_Type_recommended { get; set; }
        public string Grading_OCS { get; set; }
        public string COMPQ2 { get; set; }
        public string Division_Gender_Cluster_ACCHW { get; set; }
        public string Category_Cluster_Tennis { get; set; }
        public string TM_SEASON { get; set; }
        public string Buying_REGION { get; set; }
        public string STOCK_SPACE { get; set; }
        public string Category_Cluster_recommended_HW { get; set; }
        public string Category_Cluster_forbuy_Basketball { get; set; }
        public string Division_Gender_Cluster_recommended_AppMen { get; set; }
        public string NEO_In_Large_Store { get; set; }
        public string STA_BULK_CORE { get; set; }
        public string Division_Gender_Cluster_forbuy_ACCHW { get; set; }
        public string Category_Cluster_forbuy_Tennis { get; set; }
        public string BLRQ1 { get; set; }
        public string Grading_MB { get; set; }
        public string Grading_Kids { get; set; }
        public string Division_Gender_Cluster_recommended_ACCHW { get; set; }
        public string Comments2 { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string COMPQ3 { get; set; }
        public string Product_Channel { get; set; }
        public string Category_Cluster_OutdoorWJ { get; set; }
        public string Category_Cluster_ACC { get; set; }
        public string Category_Cluster_forbuy_ACC { get; set; }
        public string Grading_OCS_recommended { get; set; }
        public string Division_Gender_Cluster_recommended_AppWomen { get; set; }
        public string Category_Cluster_forbuy_OutdoorWJ { get; set; }
        public string STA_BULK_OCS { get; set; }
        public string Category_Cluster_recommended_TrainingW { get; set; }
        public string OCS_Grading_forbuy { get; set; }
        public string BLRQ4 { get; set; }
        public string CITY_EN { get; set; }
        public string WHS_CHANNEL { get; set; }
        public string SUB_CHANNEL { get; set; }
        public string OCS_Grading { get; set; }
        public string Seg_Business_recommended { get; set; }
        public string Division_Gender_Cluster_FTWMen { get; set; }
        public string Venue_Name { get; set; }
        public string GROSS_SPACE { get; set; }
        public int ID { get; set; }
        public string Category_Cluster_forbuy_TrainingM { get; set; }
        public string Category_Cluster_TrainingM { get; set; }
        public string Division_Gender_Cluster_forbuy_FTWMen { get; set; }
        public string STC_NEO { get; set; }
        public string Category_Cluster_recommended_Tennis { get; set; }
        public string POS_Level_Buy { get; set; }
        public string COMPQ1 { get; set; }
        public string CITY_TIER { get; set; }
        public string POS_Cluster { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string POS_Cluster_forbuy { get; set; }
        public string POS_Status { get; set; }
        public string Division_Gender_Cluster_FTWWomen { get; set; }
        public string BIG_FORMAT { get; set; }
        public string Category_Cluster_Swim { get; set; }
        public string FCST_MPSA_IN_KSR { get; set; }
        public string Category_Cluster_forbuy_Swim { get; set; }
        public string Category_Cluster_recommended_ACC { get; set; }
        public string Category_Cluster_forbuy_Football { get; set; }
        public string Category_Cluster_recommended_OutdoorWJ { get; set; }
        public string Terrex_In_Large_Store { get; set; }
        public string OCS_NS_Target { get; set; }
        public string BRANCH_EN { get; set; }
        public string BLRQ2 { get; set; }
        public string PackagePOS { get; set; }
        public string POS_NAME { get; set; }
        public string Category_Cluster_Football { get; set; }
        public string Division_Gender_Cluster_AppMen { get; set; }
        public string Category_Cluster_Outdoor { get; set; }
        public string Category_Cluster_forbuy_Outdoor { get; set; }
        public string STC_CORE { get; set; }
        public string Division_Gender_Cluster_recommended_FTWMen { get; set; }
        public string Category_Cluster_recommended_Basketball { get; set; }
        public string PROVINCE_EN { get; set; }
        public string Division_Gender_Cluster_forbuy_AppMen { get; set; }
        public string Category_Cluster_recommended_TrainingM { get; set; }
        public string Kids_in_Large_Store { get; set; }
        public string OCS_Grading_recommended { get; set; }
        public string POS_CHANNEL { get; set; }
        public string POS_Type_forbuy { get; set; }
        public string POS_Type { get; set; }
        public string Category_Cluster_HW { get; set; }
        public string AssortmentPOS { get; set; }
        public string TM_YEAR { get; set; }
        public string SELLING_SPACE { get; set; }
        public string FCST_MPSA { get; set; }
        public string Category_Cluster_TrainingW { get; set; }
        public string Category_Cluster_forbuy_TrainingW { get; set; }
        public string Division_Gender_Cluster_forbuy_FTWWomen { get; set; }
        public string CITY_CN { get; set; }
        public string STC_KIDS { get; set; }
        public string Category_Cluster_recommended_Swim { get; set; }
        public string Category_Cluster_recommended_Football { get; set; }
        public string OCS_Type_in_Large_Store { get; set; }
        public string Seg_Marketplace { get; set; }
        public string Seg_Marketplace_forbuy { get; set; }
        public string Category_Cluster_forbuy_Running { get; set; }
        public string ADDRESS { get; set; }
        public string CUSTOMER_GROUP { get; set; }
        public string Category_Cluster_Running { get; set; }
        public string POS_CODE { get; set; }
        public string COMPQ4 { get; set; }
        public string Biz_Mode { get; set; }
        public string Category_Cluster_recommended_Outdoor { get; set; }
        public string POS_Cluster_recommended { get; set; }
        public string Category_Cluster_forbuy_HW { get; set; }
        public string Region { get; set; }
        public string STA_BULK_NEO { get; set; }
        public string CURRENT_STATUS { get; set; }
        public string CURRENT_COMPSTATUS { get; set; }
        public string Category_Cluster_recommended_Training_W { get; set; }
        public string Category_Cluster_recommended_Train { get; set; }
        public string BCS_POS_TYPE { get; set; }
        public string BCS_POS_TYPE_RECOMMENDED { get; set; }
        public string POS_Type_Neo_Recommended { get; set; }
        public string POS_Type_Kids_Recommended { get; set; }
        public string POS_Type_Neo { get; set; }
        public string POS_Type_Kids { get; set; }
        public string Product_Channel_Core { get; set; }
        public string Product_Channel_NEO { get; set; }
        public string Product_Channel_OCS { get; set; }
        public string Product_Channel_KIDS { get; set; }
        public string Error_Message { get; set; }
        public string UserID { get; set; }
        public string UploadDate { get; set; }
    }
}
